import type { Dispatch, MutableRefObject, SetStateAction } from "react";
import type { SharedValue } from "react-native-reanimated";
import { AudioManager } from "../AudioManager";
import { GeminiLiveClient } from "../GeminiLiveClient";
import { MemoryEngine } from "../MemoryEngine";
import { RelationshipEngine } from "../RelationshipEngine";
import { AutonomousEventLoop } from "../AutonomousEventLoop";
import { SessionLogger } from "../SessionLogger";
import { MicGate } from "../MicGate";
import { GrowthEngine } from "../GrowthEngine";
import { TranscriptCoordinator } from "./TranscriptCoordinator";
import { PlaybackController } from "../audio/PlaybackController";
import { FillerCoordinator } from "./FillerCoordinator";
import type { EmotionState } from "../EmotionEngine";
import type { TriggerType } from "../PersonalityEngine";

export interface AppSessionRuntimeDeps {
  apiKey: string | undefined;
  setSpeechText: Dispatch<SetStateAction<string | null>>;
  setSystemStatus: Dispatch<SetStateAction<string>>;
  setEmotionState: Dispatch<SetStateAction<EmotionState>>;
  setIsSpeakingState: Dispatch<SetStateAction<boolean>>;
  appStartAtRef: MutableRefObject<number>;
  ahaTrackedRef: MutableRefObject<boolean>;
  timeSinceActionRef: MutableRefObject<number>;
  totalInteractionsRef: MutableRefObject<number>;
  sessionLoggerRef: MutableRefObject<SessionLogger>;
  emotionTimeoutRef: MutableRefObject<ReturnType<typeof setTimeout> | null>;
  geminiReadyRef: MutableRefObject<boolean>;
  audioManagerRef: MutableRefObject<AudioManager | null>;
  geminiClientRef: MutableRefObject<GeminiLiveClient | null>;
  memoryEngineRef: MutableRefObject<MemoryEngine | null>;
  relationshipEngineRef: MutableRefObject<RelationshipEngine | null>;
  autonomousLoopRef: MutableRefObject<AutonomousEventLoop | null>;
  growthEngineRef: MutableRefObject<GrowthEngine | null>;
  playbackControllerRef: MutableRefObject<PlaybackController | null>;
  micGateRef: MutableRefObject<MicGate | null>;
  transcriptCoordinatorRef: MutableRefObject<TranscriptCoordinator | null>;
  fillerCoordinatorRef: MutableRefObject<FillerCoordinator | null>;
  greetingTimerRef: MutableRefObject<ReturnType<typeof setTimeout> | null>;
  micHealthIntervalRef: MutableRefObject<ReturnType<typeof setInterval> | null>;
  responseWatchdogRef: MutableRefObject<ReturnType<typeof setInterval> | null>;
  idleTimerRef: MutableRefObject<ReturnType<typeof setInterval> | null>;
  idleFillerTimerRef: MutableRefObject<ReturnType<typeof setInterval> | null>;
  accelSubRef: MutableRefObject<{ remove: () => void } | null>;
  lastMicChunkAtRef: MutableRefObject<number>;
  lastConversationAtRef: MutableRefObject<number>;
  carModelRefusedRef: MutableRefObject<boolean>;
  waitingForGeminiRef: MutableRefObject<boolean>;
  activeTurnIdRef: MutableRefObject<string | null>;
  turnIdSequenceRef: MutableRefObject<number>;
  greetingSentOnceRef: MutableRefObject<boolean>;
  turnLatencyTrackerRef: MutableRefObject<{
    startWaiting: () => void;
    stopWaiting: () => void;
    getWaitingMs: () => number;
    getAverage: () => number | null;
    getSampleCount: () => number;
  }>;
  tiltX: SharedValue<number>;
  tiltY: SharedValue<number>;
  triggerReaction: (action: TriggerType) => void;
  onUserTranscriptFlush: (text: string) => void;
  onGeminiTranscriptFlush: (text: string) => void;
  markGeminiResponse: (source: "audio" | "transcript" | "turnComplete") => void;
  restoreMicPipeline: () => void;
  onMicPermissionDenied: () => void;
  onReconnectExhausted: () => void;
  onLookThroughCamera: () => void;
  getDriveContextSnapshot: () => Record<string, unknown>;
}
